# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: mcp-trino

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - id: mcp-trino
    main: ./cmd/mcp-trino
    binary: mcp-trino
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -a
    ldflags:
      - -s -w
      - -X github.com/txn2/mcp-trino/internal/server.Version={{.Version}}

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Sign release artifacts with Cosign (keyless - uses OIDC identity)
signs:
  - id: archives
    cmd: cosign
    artifacts: archive
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"
  - id: checksums
    cmd: cosign
    artifacts: checksum
    signature: "${artifact}.sigstore.json"
    args:
      - "sign-blob"
      - "--yes"
      - "--bundle=${signature}"
      - "${artifact}"

# Generate Software Bill of Materials for archives
sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Security
      regexp: '^security'
      order: 2
    - title: Others
      order: 999

# Docker Images - Using v2 format with multi-platform support
dockers_v2:
  - id: alpine
    dockerfile: Dockerfile
    ids:
      - mcp-trino
    images:
      - ghcr.io/txn2/mcp-trino
    tags:
      - latest
      - "{{ .Tag }}"
      - "v{{ .Major }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.description: "MCP server for Trino data warehouses"
      org.opencontainers.image.licenses: "Apache-2.0"

# Sign Docker images with Cosign (keyless)
docker_signs:
  - cmd: cosign
    args:
      - "sign"
      - "--yes"
      - "${artifact}"
    artifacts: all

release:
  github:
    owner: txn2
    name: mcp-trino
  name_template: "{{.ProjectName}}-v{{.Version}}"
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Claude Code CLI
    ```bash
    claude mcp add trino \
      -e TRINO_HOST=your-trino-host \
      -e TRINO_USER=your-user \
      -- mcp-trino
    ```

    ### Docker
    ```bash
    docker pull ghcr.io/txn2/mcp-trino:{{ .Tag }}
    ```

    ## Verification

    All release artifacts are signed. Verify with:
    ```bash
    cosign verify-blob --bundle mcp-trino_{{ .Version }}_linux_amd64.tar.gz.sigstore.json \
      mcp-trino_{{ .Version }}_linux_amd64.tar.gz
    ```

    SLSA provenance verification:
    ```bash
    slsa-verifier verify-artifact mcp-trino_{{ .Version }}_linux_amd64.tar.gz \
      --provenance-path multiple.intoto.jsonl \
      --source-uri github.com/txn2/mcp-trino
    ```
